stages:
    - Do_Prechecks
    - Reboot_Action

Do_Prechecks:
    stage: Do_Prechecks
    script:
        - chmod +x reboot_prechecks.sh
        - sh reboot_prechecks.sh
    tags:
        - gitlab-runner-test
    only:
        changes:
            - reboot.json
Reboot_Action:
    stage: Reboot_Action
    script:
        - chmod +x reboot.sh
        - sh reboot.sh
    tags:
        - gitlab-runner-test
    only:
        changes:
            - reboot.json

