stages:
    - Do_Prechecks
    - Start_Action

Do_Prechecks:
    stage: Do_Prechecks
    script:
        - chmod +x start_prechecks.sh
        - sh start_prechecks.sh
    tags:
        - gitlab-runner-test
    only:
        changes:
            - start.json
Start_Action:
    stage: Start_Action
    script:
        - chmod +x start.sh
        - sh start.sh
    tags:
        - gitlab-runner-test
    only:
        changes:
            - start.json
